Repository Leads-org/petstop, pull requests merged in 2022-10, with the labels that each got.

#6 new page products
  components/ListProducts.tsx
  components/NavCategory.tsx
  components/Ratings.tsx
  pages/products.tsx
Labels: enhancement

#18 Solve env variable issue
  .env.example
  README.md
  components/BestSeller.tsx
  components/Products.tsx
  pages/products/[productId].tsx
Labels: bug, enhancement

#20 Wrap Kontenbase API into Next.js API routes
  components/Products.tsx
  pages/api/hello.ts
  pages/api/products.ts
  pages/api/products/count.ts
  types/product.ts
Labels: bug, enhancement

#38 Implement delete product in cart by in the cart page
  components/CartList.tsx
  pages/products/[productId].tsx
Labels: bug, enhancement

#52 Fix missing conditional to get the products data by category or not
  components/Products.tsx
  pages/api/products.ts
Labels: bug
